toy_project/accounts/urls.py
from os import name
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('create_profile', views.create_profile, name="create_profile"),
    #path('modify_profile', views.modify_profile, name='modify_profile'),
    path('modify_profile/<int:pk>',
    views.modify_profile, name='modify_profile'),
]

toy_project/main/urls.py
from django.urls import path
from . import views
from django.conf.urls import include

app_name = 'main'

urlpatterns = [
    path('create/', views.create, name="create"),
    path('', views.index, name="index"),
    path('detail/<int:write_id>', views.detail, name="detail"),
    path('update/<int:write_id>', views.update, name="update"),
    path('delete/<int:write_id>', views.delete, name="delete"),
    path('create_comment/<int:write_id>',
         views.create_comment, name='create_comment'),
    path('delete_comment/<int:write_id>/<int:comment_id>',
         views.delete_comment, name='delete_comment'),
    path('map/<int:write_id>', views.map, name="map"),
    path('page/<int:write_id>', views.page, name="page"),
    path('post_like_toggle/<int:post_id>/',
         views.post_like_toggle, name="post_like_toggle"),

]

toy_project/toy_project/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('main/', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toy_project/toy_project/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block extrahead %}
    {% endblock %}
</head>

<body>
    <nav>
        <ul class="nav-container">
            <li class="nav-item"><a href="{%url 'main:index' %}">Home</a></li>
            {% if user.is_authenticated %}
            <li class="nav-item" id="username">{{user.username}}</li>
            
            {% if user.pro.nickname %}
            <li class="nav-item"><a href="{%url 'accounts:modify_profile' user.pk %}">Profile</a></li>
            {% else %}
            <li class="nav-item"><a href="{%url 'accounts:create_profile'%}">Profile</a></li>
            {% endif %}
            <li class="nav-item"><a href="{%url 'accounts:logout'%}">Logout</a></li>
            {% else %}
            
            <li class="nav-item"><a href="{%url 'accounts:login'%}">Login</a></li>
            <li class="nav-item"><a href="{%url 'accounts:signup'%}">Signup</a></li>

            {% endif %}

        </ul>
    </nav>
    {% block content %}
    {% endblock %}
</body>

</html>