toy_project/main/urls.py
from django.urls import path
from . import views
from django.conf.urls import include

app_name = 'main'

urlpatterns = [
    path('create/', views.create, name="create"),
    path('', views.index, name="index"),
    path('detail/<int:write_id>', views.detail, name="detail"),
    path('update/<int:write_id>', views.update, name="update"),
    path('delete/<int:write_id>', views.delete, name="delete"),
    path('create_comment/<int:write_id>',
         views.create_comment, name='create_comment'),
    path('delete_comment/<int:write_id>/<int:comment_id>',
         views.delete_comment, name='delete_comment'),
    path('map/<int:write_id>', views.map, name="map"),
    path('page/<int:write_id>', views.page, name="page"),
    path('post_like_toggle/<int:post_id>/',
         views.post_like_toggle, name="post_like_toggle"),

]

toy_project/toy_project/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('main/', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toy_project/main/models.py
from accounts.models import Profile
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
# from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.


class Write(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    contents = models.TextField()
    images = models.ImageField(null=True, blank=True)
    updated_at = models.DateField(auto_now=True)
    like_count = models.PositiveIntegerField(default=0)


class Comment(models.Model):
    post = models.ForeignKey(Write, related_name="comment", on_delete=CASCADE)
    user = models.ForeignKey(User, related_name="comment", on_delete=CASCADE)
    content = models.TextField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.post.title


class Map(models.Model):
    objects = models.Manager()
    input_memo = models.CharField(max_length=200, null=True)
    lat = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    lon = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    placename = models.CharField(max_length=100, null=True)
    post = models.ForeignKey(Write, related_name="report",
                             on_delete=CASCADE, null=True)

toy_project/main/forms.py
from django import forms
from django.db.models import fields
from django import forms
from .models import Write, Comment  # 나중에 작업할 때 comments 추가


class WriteForm(forms.ModelForm):
    class Meta:
        model = Write
        fields = ('title', 'contents', 'images')


class CommentForm(forms.ModelForm):
    content = forms.CharField(label='')

    class Meta:
        model = Comment
        fields = ['content']

toy_project/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import WriteForm, CommentForm
from .models import Write, Comment, Map
from django.contrib.auth.models import User
from accounts.models import Profile
from django.http.response import HttpResponse
from django.contrib.auth.decorators import login_required


# Create your views here.


def index(request):
    # all_write 변수에 내용 담아서 보내기
    all_write = Write.objects.all()
    all_profile = Profile.objects.all()
    return render(request, 'index.html', {'all_write': all_write, 'all_profile': all_profile})


@login_required
def create(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    if request.method == "POST":
        create_form = WriteForm(request.POST, request.FILES)
        if create_form.is_valid():
            create_form = create_form.save(commit=False)
            create_form.user = profile
            create_form.save()
            return redirect('index')
    write_form = WriteForm
    return render(request, 'create.html', {'write_form': write_form})


def detail(request, write_id):
    user = request.user
    my_write = get_object_or_404(Write, pk=write_id)
    profile = Profile.objects.get(user=user)
    comment_form = CommentForm()
    comments = Comment.objects.filter(post=write_id)
    map = Map.objects.filter(post=write_id)
    return render(request, 'detail.html', {'my_write': my_write, 'comment_form': comment_form, 'comments': comments, 'user': user, 'map': map, 'profile':profile})


def update(request, write_id):
    my_write = get_object_or_404(Write, id=write_id)
    if request.method == "POST":
        update_form = WriteForm(request.POST, request.FILES, instance=my_write)
        if update_form.is_valid():
            update_form.save()
            return redirect('index')
    update_form = WriteForm(instance=my_write)
    return render(request, 'update.html', {'update_form': update_form})


def delete(request, write_id):
    my_write = get_object_or_404(Write, id=write_id)
    my_write.delete()
    return redirect('index')


def create_comment(request, write_id):
    if request.method == "POST":
        # POST 요청으로 넘어온 데이터를 CommentForm 양식에 넣고 comment 변수에 담기
        comment = CommentForm(request.POST)
        if comment.is_valid:  # 해당 폼이 유효한 경우 저장하고 detail.html로 돌아가기
            form = comment.save(commit=False)
            user = request.user
            form.user = User.objects.get(id=user.id)  # user 필드에 값 추가
            form.post = Write.objects.get(id=write_id)  # post 필드에 값 추가
            form.save()
        return redirect("main:detail", write_id)


def delete_comment(request, write_id, comment_id):
    my_comment = get_object_or_404(Comment, id=comment_id)
    my_comment.delete()
    return redirect("main:detail", write_id)


@login_required
def post_like_toggle(request, post_id):
    post = get_object_or_404(Write, pk=post_id)
    user = request.user
    profile = Profile.objects.get(user=user)

    try:
        check_like = profile.like_post.get(id=post_id)
        profile.like_post.remove(post)
        post.like_count -= 1
        post.save()
    except:
        profile.like_post.add(post)
        post.like_count += 1
        post.save()
    return redirect('main:detail', post_id)


def page(request, write_id):
    my_write = get_object_or_404(Write, id=write_id)
    return render(request, 'map.html', {'my_write': my_write})


def map(request, write_id):
    my_write = get_object_or_404(Write, id=write_id)
    if request.method == "POST":
        map = Map()
        map.lat = request.POST['lat']
        map.lon = request.POST['lon']
        map.placename = request.POST['placename']
        map.post = Write.objects.get(id=write_id)
        map.save()
        return HttpResponse(content_type='application/json')

toy_project/main/templates/create.html
{% extends 'base.html' %} {% load static %} 

{% block extrahead %}

<link rel="stylesheet" href="{% static 'css/create.css' %}" >

{% endblock %}
{% block content %}
<div class="container">
  <form method="POST", enctype="multipart/form-data">
    {% csrf_token %}
    {{write_form.as_p}}
    <div id="upload"><input type="submit" value="UPLOAD" /></div>
  </form>
</div>

{% endblock %}

toy_project/main/templates/detail.html
{% extends 'base.html' %} {% load static %}

{% block extrahead %}

<link rel="stylesheet" href="{% static 'css/detail.css' %}">

{% endblock %}
{% block content %}
<div class="write">
  <div class="container">
    <div class="image">
      {% if my_write.images %}
      <img src="{{my_write.images.url}}">
      {% endif %}
    </div>

    <div class="contents">
      <div class="content">
        <div id="title">{{my_write.title}}</div>
        <div id="date">{{my_write.updated_at}}</div>
        <div id="button"><a href="{%url 'main:update' my_write.id %}"><button>| 수정</button></a>
          <a href="{%url 'main:delete' my_write.id %}"><button>| 삭제</button></a>
          <a href="{%url 'main:page' my_write.id %}"><button>| 지도추가</button></a><br>
        </div>

        <hr noshade="" color="black" size="1.5">
        <div id="content">{{my_write.contents}}</div>
        <div class="like">
          <a href="{% url 'main:post_like_toggle' my_write.id %}">
      
            {% if my_write in profile.like_post.all %}
            <img id="heart" src="{%static 'images/heart.png'%}">
            {% else %}
            <img id="empty_heart" src="{%static 'images/empty_heart.png'%}">
            {% endif %}
          </a>
          <span>{{my_write.like_count}}</span> 
        </div>
      </div>
    </div>
  </div>
  
  {% if map%}
  <div id="place">
    <p>TRAVEL ROUTE</p>
    {% for map in map.all %}
    <tr>
      <td>{{ map.placename }} > </td>
    </tr>
    {% endfor %}
  </div>
  <div id="map" style="width:100%;height:400px;"></div>
  <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=e4629dfd6293cb3c36858f5010d2a71e&libraries=services"></script>
  {%endif%}
  <script>
      // 마커를 클릭하면 장소명을 표출할 인포윈도우 입니다
      var infowindow = new kakao.maps.InfoWindow({zIndex:1});
       
      var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
          mapOption = {
              center: new kakao.maps.LatLng(37.539448, 126.987477), // 지도의 중심좌표
              level: 3 // 지도의 확대 레벨
          };  
      var map = new kakao.maps.Map(mapContainer, mapOption); 
      var infowindow = new kakao.maps.InfoWindow({zIndex:1});
      var imageSrc = "https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/markerStar.png"; 
      var bounds = new kakao.maps.LatLngBounds();
      
      var positions =[
          {% for i in map %}
             {
                  lat : {{i.lat}},
                  lon : {{i.lon}},
                  title : '{{i.placename}}',
                  latlng : new kakao.maps.LatLng({{i.lat}},{{i.lon}})
                },
            {% endfor %}
          ]; 
               
      
          for (var i = 0; i < positions.length; i ++) {
              
              // 마커 이미지의 이미지 크기 입니다
              var imageSize = new kakao.maps.Size(24, 35); 
              
              // 마커 이미지를 생성합니다    
              var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize); 
              
              // 마커를 생성합니다
              var marker = new kakao.maps.Marker({
                  map: map, // 마커를 표시할 지도
                  position: positions[i].latlng, // 마커를 표시할 위치
                  title : positions[i].title, // 마커의 타이틀, 마커에 마우스를 올리면 타이틀이 표시됩니다
                  image : markerImage // 마커 이미지 
              });
              bounds.extend(positions[i].latlng);
        
          }  
            
              // LatLngBounds 객체에 추가된 좌표들을 기준으로 지도의 범위를 재설정합니다
              // 이때 지도의 중심좌표와 레벨이 변경될 수 있습니다
              map.setBounds(bounds);
          
      
      
      </script>

  <div class="comments">
    {% for comment in comments %}
    <span id="username">{{comment.user}}</span>
    <span id="comment_time">| {{comment.updated_at}}</span>
    <div id="comment">{{comment.content}}</div>
    <div id="delete_button"><a href="{% url 'main:delete_comment' my_write.id comment.id%}">삭제</a></div><br>
    <hr>
    <br><br>
    {%endfor%}
  </div>
  <div class="create_comments">
    {% if user.is_authenticated %}
    <form method="POST" action="{% url 'main:create_comment' my_write.id %}">
      {% csrf_token %}
      {{comment_form}}
      <span id="create_button"><button type="submit"><img src="{%static 'images/plane.png'%}"></button></span>
    </form>
    {%endif%}
  </div>

  {% endblock %}

toy_project/main/templates/index.html
{% extends 'base.html' %} {% load static %} {% block extrahead %}

<link rel="stylesheet" href="{% static 'css/index.css' %}">

{% endblock %} {% block title %}title{% endblock %} {% block content %}

<div class="main">
  <div class="wrapper">
    <img src="{%static 'images/main.jpg'%}" alt="" />
  </div>

  <h1>TRIP-LOG</h1>
</div>

<div class="write_wrapper">
  {% for write in all_write %}
  <a href="{% url 'main:detail' write.id %}">
    <div class="all_write">
      <div class="contents">
        <div id="title">{{write.title}}</div>
        

        <hr noshade="" color="white" size="1.5">
        <div id="content">{{write.contents}}</div>
        <div id="date">{{write.updated_at|date:"Y.m.d"}}</div>
        <div class="heart">
          <img src="{%static 'images/heart.png'%}"></span>
          {{write.like_count}}
        </div>
      </div>

      {% if write.images %}
      <img src="{{write.images.url}}">
      {% endif %}
    </div>
  </a>
  {%endfor%}

  <div class="create">
    <div class="create_write">
      {% if user.pro.nickname %}
      <div class="create_btn">
        <button><a href="{% url 'main:create' %}">NEW POST</a></button>
      </div>
      {% endif %}
    </div>
  </div>
  <footer>
    <a href="mailto:">Contact Us</a>
  </footer>
</div>


{% endblock %}

toy_project/main/templates/map.html
{% extends 'base.html' %} {% load static %} 
{% block extrahead %}

<link rel="stylesheet" href="{% static 'css/map.css' %}" >

{% endblock %}
{% block content %}
<p>키워드 검색 후 지도를 클릭하세요!</p> 
<style>
    .map_wrap, .map_wrap * {margin:0;padding:0;font-family:'Malgun Gothic',dotum,'돋움',sans-serif;font-size:12px;}
    .map_wrap a, .map_wrap a:hover, .map_wrap a:active{color:#000;text-decoration: none;}
    .map_wrap {position:relative;width:100%;height:500px;}
    #menu_wrap {position:absolute;top:0;left:0;bottom:0;width:250px;margin:10px 0 30px 10px;padding:5px;overflow-y:auto;background:rgba(255, 255, 255, 0.7);z-index: 1;font-size:12px;border-radius: 10px;}
    .bg_white {background:#fff;}
    #menu_wrap hr {display: block; height: 1px;border: 0; border-top: 2px solid #5F5F5F;margin:3px 0;}
    #menu_wrap .option{text-align: center;}
    #menu_wrap .option p {margin:10px 0;}  
    #menu_wrap .option button {margin-left:5px;}
    #placesList li {list-style: none;}
    #placesList .item {position:relative;border-bottom:1px solid #888;overflow: hidden;cursor: pointer;min-height: 65px;}
    #placesList .item span {display: block;margin-top:4px;}
    #placesList .item h5, #placesList .item .info {text-overflow: ellipsis;overflow: hidden;white-space: nowrap;}
    #placesList .item .info{padding:10px 0 10px 55px;}
    #placesList .info .gray {color:#8a8a8a;}
    #placesList .info .jibun {padding-left:26px;background:url(https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/places_jibun.png) no-repeat;}
    #placesList .info .tel {color:#009900;}
    #placesList .item .markerbg {float:left;position:absolute;width:36px; height:37px;margin:10px 0 0 10px;background:url(https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_number_blue.png) no-repeat;}
    #placesList .item .marker_1 {background-position: 0 -10px;}
    #placesList .item .marker_2 {background-position: 0 -56px;}
    #placesList .item .marker_3 {background-position: 0 -102px}
    #placesList .item .marker_4 {background-position: 0 -148px;}
    #placesList .item .marker_5 {background-position: 0 -194px;}
    #placesList .item .marker_6 {background-position: 0 -240px;}
    #placesList .item .marker_7 {background-position: 0 -286px;}
    #placesList .item .marker_8 {background-position: 0 -332px;}
    #placesList .item .marker_9 {background-position: 0 -378px;}
    #placesList .item .marker_10 {background-position: 0 -423px;}
    #placesList .item .marker_11 {background-position: 0 -470px;}
    #placesList .item .marker_12 {background-position: 0 -516px;}
    #placesList .item .marker_13 {background-position: 0 -562px;}
    #placesList .item .marker_14 {background-position: 0 -608px;}
    #placesList .item .marker_15 {background-position: 0 -654px;}
    #pagination {margin:10px auto;text-align: center;}
    #pagination a {display:inline-block;margin-right:10px;}
    #pagination .on {font-weight: bold; cursor: default;color:#777;}
    </style>
  </head>
      <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <div class="map_wrap">
        <div id="map" style="width:100%;height:100%;position:relative;overflow:hidden;"></div>
    
        <div id="menu_wrap" class="bg_white">
            <div class="option">
                <div>
                    <form onsubmit="searchPlaces(); return false;">
                        키워드 : <input type="text" value="이태원 맛집" id="keyword" size="15"> 
                        <button type="submit">검색하기</button> 
                    </form>
                </div>
            </div>
            <hr>
            <ul id="placesList"></ul>
            <div id="pagination"></div>
        </div>
    </div>
  
  

    <div id="result"></div>
    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=e4629dfd6293cb3c36858f5010d2a71e&libraries=services"></script>
    <script>
    // 마커를 담을 배열입니다
    var markers = [];
    
    var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
        mapOption = {
            center: new kakao.maps.LatLng(37.566826, 126.9786567), // 지도의 중심좌표
            level: 3 // 지도의 확대 레벨
        };  
        selectedMarker = null;
    
    // 지도를 생성합니다    
    var map = new kakao.maps.Map(mapContainer, mapOption); 
    
    // 장소 검색 객체를 생성합니다
    var ps = new kakao.maps.services.Places();  
    
    // 검색 결과 목록이나 마커를 클릭했을 때 장소명을 표출할 인포윈도우를 생성합니다
    var infowindow = new kakao.maps.InfoWindow({zIndex:1});
    
    // 키워드로 장소를 검색합니다
    searchPlaces();
    
    // 키워드 검색을 요청하는 함수입니다
    function searchPlaces() {
    
        var keyword = document.getElementById('keyword').value;
    
        if (!keyword.replace(/^\s+|\s+$/g, '')) {
            alert('키워드를 입력해주세요!');
            return false;
        }
    
        // 장소검색 객체를 통해 키워드로 장소검색을 요청합니다
        ps.keywordSearch( keyword, placesSearchCB); 
    }
    
    // 장소검색이 완료됐을 때 호출되는 콜백함수 입니다
    function placesSearchCB(data, status, pagination) {
        if (status === kakao.maps.services.Status.OK) {
    
            // 정상적으로 검색이 완료됐으면
            // 검색 목록과 마커를 표출합니다
            displayPlaces(data);
    
            // 페이지 번호를 표출합니다
            displayPagination(pagination);
    
        } else if (status === kakao.maps.services.Status.ZERO_RESULT) {
    
            alert('검색 결과가 존재하지 않습니다.');
            return;
    
        } else if (status === kakao.maps.services.Status.ERROR) {
    
            alert('검색 결과 중 오류가 발생했습니다.');
            return;
    
        }
    }
    
    // 검색 결과 목록과 마커를 표출하는 함수입니다
    function displayPlaces(places) {
    
        var listEl = document.getElementById('placesList'), 
        menuEl = document.getElementById('menu_wrap'),
        fragment = document.createDocumentFragment(), 
        bounds = new kakao.maps.LatLngBounds(), 
        listStr = '';
        
        // 검색 결과 목록에 추가된 항목들을 제거합니다
        removeAllChildNods(listEl);
    
        // 지도에 표시되고 있는 마커를 제거합니다
        removeMarker();
        
        for ( var i=0; i<places.length; i++ ) {
    
            // 마커를 생성하고 지도에 표시합니다
            var placePosition = new kakao.maps.LatLng(places[i].y, places[i].x),
                marker = addMarker(placePosition, i,  places[i].placename), 
                itemEl = getListItem(i, places[i]); // 검색 결과 항목 Element를 생성합니다
    
            // 검색된 장소 위치를 기준으로 지도 범위를 재설정하기위해
            // LatLngBounds 객체에 좌표를 추가합니다
            bounds.extend(placePosition);
    
            // 마커와 검색결과 항목에 mouseover 했을때
            // 해당 장소에 인포윈도우에 장소명을 표시합니다
            // mouseout 했을 때는 인포윈도우를 닫습니다
            (function(marker, title) {
                marker.setTitle(title);
  
                kakao.maps.event.addListener(marker, 'mouseover', function() {
                    displayInfowindow(marker, title);
                });
    
                kakao.maps.event.addListener(marker, 'mouseout', function() {
                    infowindow.close();
                });
    
                itemEl.onmouseover =  function () {
                    displayInfowindow(marker, title);
                };
    
                itemEl.onmouseout =  function () {
                    infowindow.close();
                };
            })(marker, places[i].place_name);
    
            fragment.appendChild(itemEl);
        }
    
        // 검색결과 항목들을 검색결과 목록 Elemnet에 추가합니다
        listEl.appendChild(fragment);
        menuEl.scrollTop = 0;
    
        // 검색된 장소 위치를 기준으로 지도 범위를 재설정합니다
        map.setBounds(bounds);
    }
    
    // 검색결과 항목을 Element로 반환하는 함수입니다
    function getListItem(index, places) {
    
        var el = document.createElement('li'),
        itemStr = '<span class="markerbg marker_' + (index+1) + '"></span>' +
                    '<div class="info">' +
                    '   <h5>' + places.place_name + '</h5>';
    
        if (places.road_address_name) {
            itemStr += '    <span>' + places.road_address_name + '</span>' +
                        '   <span class="jibun gray">' +  places.address_name  + '</span>';
        } else {
            itemStr += '    <span>' +  places.address_name  + '</span>'; 
        }
                    
          itemStr += '  <span class="tel">' + places.phone  + '</span>' +
                    '</div>';           
    
        el.innerHTML = itemStr;
        el.className = 'item';
    
        return el;
    }
    
    // 마커를 생성하고 지도 위에 마커를 표시하는 함수입니다
    function addMarker(position, idx, title) {
        var imageSrc = 'https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_number_blue.png', // 마커 이미지 url, 스프라이트 이미지를 씁니다
            imageSize = new kakao.maps.Size(36, 37),  // 마커 이미지의 크기
            imgOptions =  {
                spriteSize : new kakao.maps.Size(36, 691), // 스프라이트 이미지의 크기
                spriteOrigin : new kakao.maps.Point(0, (idx*46)+10), // 스프라이트 이미지 중 사용할 영역의 좌상단 좌표
                offset: new kakao.maps.Point(13, 37) // 마커 좌표에 일치시킬 이미지 내에서의 좌표
            },
            markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize, imgOptions),
                marker = new kakao.maps.Marker({
                position: position, // 마커의 위치
                image: markerImage,
              
            });
                
                    marker.setMap(map); // 지도 위에 마커를 표출합니다
                    markers.push(marker);  // 배열에 생성된 마커를 추가합니다
                    kakao.maps.event.addListener(marker, 'click', function() {
  
            // 클릭된 마커가 없고, click 마커가 클릭된 마커가 아니면
            // 마커의 이미지를 클릭 이미지로 변경합니다
            if (!selectedMarker || selectedMarker !== marker) {
  
                // 클릭된 마커 객체가 null이 아니면
                // 클릭된 마커의 이미지를 기본 이미지로 변경하고
                !!selectedMarker && selectedMarker.setImage(selectedMarker.normalImage);
  
                var latlng = marker.getPosition();
                var thistitle = document.getElementById('placename');
                // 현재 클릭된 마커의 이미지는 클릭 이미지로 변경합니다
                var message = '클릭한 위치는 ' + marker.getTitle();
                //message += '경도는 ' + latlng.getLng() + ' 입니다';
  
                // var resultDiv = document.getElementById('result'); 
                
               // resultDiv.innerHTML = message;
  
                var newItem = document.createElement("div");
                newItem.innerHTML = message;
                document.getElementById("result").appendChild(newItem);
  
                $("#btn-save").click(function () {
                
                $.ajax({
                type: "POST",
                url: "{% url 'main:map' my_write.id %}",
                data: { 'csrfmiddlewaretoken': '{{ csrf_token }}', 'lat': latlng.getLat(), 'lon':latlng.getLng(),'placename':marker.getTitle() },
                dataType: "text",
                success: function (data) {
                    console.log('성공');
                    location.replace("{% url 'main:index' %}");
                },
                error: function (request, status, error) {
                    console.log('실패');
                    console.log(request);
                    console.log(error);
                }
                }); // ajax END
            }) // btn END
            }
  
            // 클릭된 마커를 현재 클릭된 마커 객체로 설정합니다
            selectedMarker = marker;
            });
  
        return marker;
    }
    
    // 지도 위에 표시되고 있는 마커를 모두 제거합니다
    function removeMarker() {
        for ( var i = 0; i < markers.length; i++ ) {
            markers[i].setMap(null);
        }   
        markers = [];
    }
    
    // 검색결과 목록 하단에 페이지번호를 표시는 함수입니다
    function displayPagination(pagination) {
        var paginationEl = document.getElementById('pagination'),
            fragment = document.createDocumentFragment(),
            i; 
    
        // 기존에 추가된 페이지번호를 삭제합니다
        while (paginationEl.hasChildNodes()) {
            paginationEl.removeChild (paginationEl.lastChild);
        }
    
        for (i=1; i<=pagination.last; i++) {
            var el = document.createElement('a');
            el.href = "#";
            el.innerHTML = i;
    
            if (i===pagination.current) {
                el.className = 'on';
            } else {
                el.onclick = (function(i) {
                    return function() {
                        pagination.gotoPage(i);
                    }
                })(i);
            }
    
            fragment.appendChild(el);
        }
        paginationEl.appendChild(fragment);
    }
    
    // 검색결과 목록 또는 마커를 클릭했을 때 호출되는 함수입니다
    // 인포윈도우에 장소명을 표시합니다
    function displayInfowindow(marker, title) {
        var content = '<div style="padding:5px;z-index:1;">' + title + '</div>';
    
        infowindow.setContent(content);
        infowindow.open(map, marker);
    }
    
    // 검색결과 목록의 자식 Element를 제거하는 함수입니다
    function removeAllChildNods(el) {   
        while (el.hasChildNodes()) {
            el.removeChild (el.lastChild);
        }
    }
    </script>
      <div id="list"></div>

   <form method="POST" action="{% url 'main:map' my_write.id %}">
    {%csrf_token%} 
    <input type="text" id="input_report" name="input_report" placeholder="Check">    
    <input type="button" id="btn-save" name="btn-save" value="저장하기" />
    {% endblock %}

toy_project/main/templates/update.html
{% extends 'base.html' %} {% load static %} 

{% block extrahead %}

<link rel="stylesheet" href="{% static 'css/update.css' %}" >

{% endblock %}

{% block content %}
<div class="container">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %} 
    {{update_form.media}}
    {{update_form.as_p}}
    <div id="upload"><input type="submit" value="UPDATE" /></div>
  </form>
</div>

{% endblock %}